- name: Deploy the project
  hosts: all
  vars_files:
    - vars/secrets.yml
    - vars/project.yml

  roles:

    - role: common
      common_fix_sudoers: yes
      common_sudoers_file_to_remove: debian-cloud-init
      tags: ['base', ]

    - role: postgres-install

    - role: nginx
      nginx_delete_default_site: yes
      nginx_catchall_enable: yes
      nginx_override_conf: |
        server_names_hash_bucket_size 128;

    - role: acme-nginx
      acme_domains:
        - "{{ host_public_domain_name }}"
      when: host_enable_acme_ssl|default(False)
      tags: ['acme', ]

    - role: django
      tags: ['django', ]

    - role: machina-demo
      tags: ['django', 'demo', ]
